### ISSUE TITLE
Optimizing Parallelization

### ISSUE THREAD

**Issue by CodyCBakerPhD** [dandi/dandi-hub#33]
Hey all,

As I'm running a big task on the Hub I'm trying to get the most out of available resources on a extra large spawn.

![image](https://user-images.githubusercontent.com/51133164/164992430-da6d439d-8e18-47aa-ab9d-35ce0267fa4d.png)

However, both my own scripts and `dandi upload` trigger the above display, and no matter how many jobs I try to parallelize over, the actual I/O all seems capped at 8 concurrent processes according to `top` (the other tasks will show up as queued in that they have PIDs, but zero activity).

Is this intended?

**Comment by satra** [comment]
@CodyCBakerPhD - for the hub itself that extra large corresponds to the following pod resource settings, which means a guarantee of 24 CPU seconds per second. 

```yaml
    - display_name: "Extra large"
      description: "24C/64G upto 48C/96G. May take up to 15 mins to start."
      kubespawner_override:
        singleuser_image_spec: 'dandiarchive/dandihub:latest'
        image_pull_policy: Always
        cpu_limit: 48
        cpu_guarantee: 24
        mem_limit: 96G
        mem_guarantee: 64G
```

although the terminal itself will see all cores of the node. however, you should be able to get up to the guaranteed cycles. however, this is a little more complicated. this post discusses some of the details: https://www.sobyte.net/post/2022-04/k8s-cpu-limit/

for dandi upload, there are some limits, for upload there is a `-J` flag that can be used to control processes/threads.

cc/ yarikoptic
