### ISSUE TITLE
redo matlab container image

### ISSUE THREAD

**Issue by satra** [dandi/dandi-hub#37]
the following profile allows running matlab in the hub, but the container does not provide other goodies (git, datalad, dandi, etc.,.). the container should be extended to include some of the dandi tools.

```
    - display_name: "Base (MATLAB)"
      description: "6 CPU / 16 GB upto 12C/32G. May take up to 15 mins to start. This requires your own license."
      kubespawner_override:
        singleuser_image_spec: 'ghcr.io/mathworks-ref-arch/matlab-integration-for-jupyter/jupyter-byoi-matlab-notebook:r2022a'
        image_pull_policy: Always
        cpu_limit: 12
        cpu_guarantee: 6
        mem_limit: 32G
        mem_guarantee: 16G
```
